

















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConStr`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `server=5656b3001154f.sh.cdb.myqcloud.com;port=8237;database=db_light;uid=root;pwd=1qaz!QAZ;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `MySqlClientFactory`

// -----------------------------------------------------------------------------------------
// SP function creation is not supported for  `MySql.Data.MySqlClient`
// -----------------------------------------------------------------------------------------
 