

















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConStr`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `server=rds56wk7qzmkec7j58lx1.mysql.rds.aliyuncs.com;database=r76vh4e95ql22lzi;uid=r76vh4e95ql22lzi;pwd=gaoning5239319;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `MySqlClientFactory`

// -----------------------------------------------------------------------------------------
// SP function creation is not supported for  `MySql.Data.MySqlClient`
// -----------------------------------------------------------------------------------------
 